import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed": "#ff8928",
        "primary-container": "#f58220",
        "secondary-fixed-dim": "#d6d4d3",
        "tertiary-container": "#f8c229",
        "secondary-fixed": "#e5e2e1",
        "on-error-container": "#ffd2c8",
        "inverse-surface": "#111827",
        surface: "#f7f7f5",
        secondary: "#6b7280",
        "on-secondary-fixed": "#403f3f",
        "error-container": "#b92902",
        "on-background": "#111827",
        outline: "#9ca3af",
        "inverse-primary": "#974a00",
        "surface-container": "#f3f4f6",
        "secondary-container": "#e5e7eb",
        "surface-tint": "#ff923e",
        "primary-dim": "#f17f1d",
        "outline-variant": "#d1d5db",
        "surface-container-low": "#ffffff",
        "on-error": "#450900",
        "on-secondary-fixed-variant": "#5c5b5b",
        "tertiary-fixed": "#f8c229",
        primary: "#ff923e",
        "on-surface": "#111827",
        "on-tertiary-container": "#543f00",
        "tertiary-fixed-dim": "#e8b417",
        "tertiary-dim": "#e8b417",
        "on-primary": "#4d2300",
        "surface-container-lowest": "#ffffff",
        "surface-container-highest": "#e5e7eb",
        "surface-dim": "#0e0e0e",
        "on-surface-variant": "#4b5563",
        "on-primary-fixed": "#190700",
        "on-secondary-container": "#d2d0cf",
        "on-tertiary-fixed-variant": "#5f4800",
        "secondary-dim": "#d6d4d3",
        error: "#ff7351",
        "on-primary-fixed-variant": "#542600",
        tertiary: "#ffd162",
        "on-primary-container": "#3c1900",
        "on-secondary": "#374151",
        "on-tertiary": "#5f4700",
        "primary-fixed-dim": "#ee7d19",
        "on-tertiary-fixed": "#3c2c00",
        "surface-variant": "#e5e7eb",
        "surface-container-high": "#eceff3",
        background: "#f7f7f5",
        "inverse-on-surface": "#f9fafb",
        "surface-bright": "#ffffff",
        "error-dim": "#d53d18",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["var(--font-space-grotesk)"],
        body: ["var(--font-manrope)"],
        label: ["var(--font-manrope)"],
      },
    },
  },
  plugins: [],
};

export default config;
