import type { Config } from "tailwindcss";
import typography from "@tailwindcss/typography";

const config: Config = {
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        foreground: "hsl(var(--foreground))",
        card: "hsl(var(--card))",
        "card-foreground": "hsl(var(--card-foreground))",
        popover: "hsl(var(--popover))",
        "popover-foreground": "hsl(var(--popover-foreground))",
        muted: "hsl(var(--muted))",
        "muted-foreground": "hsl(var(--muted-foreground))",
        accent: "hsl(var(--accent))",
        "accent-foreground": "hsl(var(--accent-foreground))",
        destructive: "hsl(var(--destructive))",
        success: "hsl(var(--success))",
        warning: "hsl(var(--warning))",
        info: "hsl(var(--info))",
        "primary-fixed": "#ff8928",
        "primary-container": "#f58220",
        "secondary-fixed-dim": "#d6d4d3",
        "tertiary-container": "#f8c229",
        "secondary-fixed": "#e5e2e1",
        "on-error-container": "#ffd2c8",
        "inverse-surface": "#111827",
        surface: "#f7f7f5",
        secondary: "#6b7280",
        "on-secondary-fixed": "#403f3f",
        "error-container": "#b92902",
        "on-background": "#111827",
        outline: "#9ca3af",
        "inverse-primary": "#974a00",
        "surface-container": "#f3f4f6",
        "secondary-container": "#e5e7eb",
        "surface-tint": "#ff923e",
        "primary-dim": "#f17f1d",
        "outline-variant": "#d1d5db",
        "surface-container-low": "#ffffff",
        "on-error": "#450900",
        "on-secondary-fixed-variant": "#5c5b5b",
        "tertiary-fixed": "#f8c229",
        primary: "#ff923e",
        "on-surface": "#111827",
        "on-tertiary-container": "#543f00",
        "tertiary-fixed-dim": "#e8b417",
        "tertiary-dim": "#e8b417",
        "on-primary": "#4d2300",
        "surface-container-lowest": "#ffffff",
        "surface-container-highest": "#e5e7eb",
        "surface-dim": "#0e0e0e",
        "on-surface-variant": "#4b5563",
        "on-primary-fixed": "#190700",
        "on-secondary-container": "#d2d0cf",
        "on-tertiary-fixed-variant": "#5f4800",
        "secondary-dim": "#d6d4d3",
        error: "#ff7351",
        "on-primary-fixed-variant": "#542600",
        tertiary: "#ffd162",
        "on-primary-container": "#3c1900",
        "on-secondary": "#374151",
        "on-tertiary": "#5f4700",
        "primary-fixed-dim": "#ee7d19",
        "on-tertiary-fixed": "#3c2c00",
        "surface-variant": "#e5e7eb",
        "surface-container-high": "#eceff3",
        background: "#f7f7f5",
        "inverse-on-surface": "#f9fafb",
        "surface-bright": "#ffffff",
        "error-dim": "#d53d18",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["var(--font-space-grotesk)"],
        body: ["var(--font-manrope)"],
        label: ["var(--font-manrope)"],
      },
      fontSize: {
        "display-xl": [
          "clamp(72px, 10vw, 140px)",
          { lineHeight: "0.95", fontWeight: "800", letterSpacing: "-0.03em" },
        ],
        "display-lg": [
          "clamp(48px, 7vw, 96px)",
          { lineHeight: "1.0", fontWeight: "800", letterSpacing: "-0.02em" },
        ],
        headline: [
          "clamp(32px, 4vw, 56px)",
          { lineHeight: "1.1", fontWeight: "700", letterSpacing: "-0.01em" },
        ],
        title: ["clamp(20px, 2.5vw, 32px)", { lineHeight: "1.2", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.7", fontWeight: "400" }],
        "label-sm": ["11px", { lineHeight: "1.4", fontWeight: "600", letterSpacing: "0.15em" }],
      },
      spacing: {
        "section-y": "120px",
        "section-y-md": "80px",
        "section-y-sm": "60px",
        "content-max": "1280px",
        gutter: "48px",
        "gutter-sm": "24px",
      },
      keyframes: {
        "social-marquee": {
          "0%": { transform: "translateY(0)" },
          "100%": { transform: "translateY(-50%)" },
        },
      },
      animation: {
        "social-marquee": "social-marquee 22s linear infinite",
      },
    },
  },
  plugins: [
    typography({
      className: "prose",
    }),
  ],
};

export default config;
